<a href="https://colab.research.google.com/github/alkhaldieid/models/blob/master/Copy_of_Untitled11.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
from google.colab import drive
drive.mount('/content/gdrive')

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3aietf%3awg%3aoauth%3a2.0%3aoob&response_type=code&scope=email%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdocs.test%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive%20https%3a%2f%2fwww.googleapis.com%2fauth%2fdrive.photos.readonly%20https%3a%2f%2fwww.googleapis.com%2fauth%2fpeopleapi.readonly

Enter your authorization code:
··········
Mounted at /content/gdrive


In [0]:
cd /content/gdrive/My\ Drive


/content/gdrive/My Drive


In [0]:
!pip install pandas
!pip install request


In [0]:
import pandas as pd
data = pd.read_excel('1.0 Deck Structure.xlsx', index_col=0)

In [0]:
data

STRUCTURE NUMBER  HIGHWAY DISTRICT  ...  Deck Structure Type  AGE
YEAR                                      ...                          
1992            103454                 9  ...                    1   31
1992            137308                 9  ...                    2   40
1992            333123                 3  ...                    1   37
1992            430676                 4  ...                    1   51
1992            430684                 4  ...                    1   51
...                ...               ...  ...                  ...  ...
2018           8803625                 1  ...                    1   34
2018           8803749                 1  ...                    1   33
2018           8836809                 1  ...                    2   27
2018           8838984                 1  ...                    1   40
2018           8843260                 1  ...                    2   27

[77625 rows x 14 columns]

In [0]:
data.shape

(77625, 14)

In [0]:
labels = data['Deck Condition']
print(labels)

YEAR
1992    6
1992    5
1992    6
1992    8
1992    8
       ..
2018    6
2018    7
2018    7
2018    7
2018    7
Name: Deck Condition, Length: 77625, dtype: int64


In [0]:
columns = list(data)

In [0]:
columns

['STRUCTURE NUMBER',
 'HIGHWAY DISTRICT',
 'YEAR BUILT',
 'ADT',
 'Design Load',
 'Skew',
 'Design Type',
 'Type of Support',
 'Number of Spans in Main Unit',
 'Structure Length',
 'Deck Width',
 'Deck Condition',
 'Deck Structure Type',
 'AGE']

In [0]:
npdata = data.values
print(npdata)

[[103454 9 1960 ... 6 1 31]
 [137308 9 1951 ... 5 2 40]
 [333123 3 1954 ... 6 1 37]
 ...
 [8836809 1 1990 ... 7 2 27]
 [8838984 1 1977 ... 7 1 40]
 [8843260 1 1990 ... 7 2 27]]


In [0]:
import numpy as np
np.shape(npdata)

(77625, 14)

In [0]:
len(columns)

14

In [0]:
unnumData = npdata[:,1:]
print(np.shape(unnumData))

(77625, 13)


In [0]:
unnumData

array([[9, 1960, 1920, ..., 6, 1, 31],
       [9, 1951, 150, ..., 5, 2, 40],
       [3, 1954, 1354, ..., 6, 1, 37],
       ...,
       [1, 1990, 324, ..., 7, 2, 27],
       [1, 1977, 324, ..., 7, 1, 40],
       [1, 1990, 112, ..., 7, 2, 27]], dtype=object)

In [0]:
unnumData[0]

array([9, 1960, 1920, 2, 10, 1, 2, 3, 34.1, 12.1999999999999, 6, 1, 31],
      dtype=object)

In [0]:
unnumData92 = unnumData[:2875,:]
print(unnumData92)
print(np.shape(unnumData))

[[9 1960 1920 ... 6 1 31]
 [9 1951 150 ... 5 2 40]
 [3 1954 1354 ... 6 1 37]
 ...
 [1 1990 50 ... 9 2 0]
 [1 1977 50 ... 7 1 13]
 [1 1990 50 ... 9 2 0]]
(77625, 13)


In [0]:
unnumFeatures92 = np.delete(unnumData92, [10], axis=1)
print(unnumFeatures92)

[[9 1960 1920 ... 12.1999999999999 1 31]
 [9 1951 150 ... 6.7 2 40]
 [3 1954 1354 ... 13.6 1 37]
 ...
 [1 1990 50 ... 8.5 2 0]
 [1 1977 50 ... 6.59999999999999 1 13]
 [1 1990 50 ... 7.5 2 0]]


In [0]:
unclean = []
for i in range(np.shape(unnumFeatures92)[0]):
  for j in range(np.shape(unnumFeatures92)[1]):
    if isinstance(unnumFeatures92[i,j], str):
      unclean.append([i,j])
print(unclean)
len(unclean)

[[29, 10], [48, 6], [148, 6], [191, 6], [201, 6], [442, 6], [448, 6], [453, 6], [469, 6], [477, 6], [478, 6], [481, 6], [483, 6], [488, 6], [491, 6], [492, 6], [514, 6], [518, 6], [542, 6], [544, 6], [545, 6], [546, 6], [615, 6], [617, 6], [618, 6], [661, 6], [763, 6], [807, 6], [808, 10], [810, 10], [811, 10], [814, 10], [815, 10], [818, 10], [819, 10], [820, 10], [975, 6], [979, 6], [1016, 6], [1018, 6], [1060, 6], [1063, 6], [1079, 6], [1107, 6], [1112, 6], [1235, 6], [1237, 6], [1241, 6], [1242, 6], [1247, 6], [1249, 6], [1250, 6], [1263, 6], [1267, 6], [1268, 6], [1272, 6], [1283, 6], [1285, 6], [1304, 6], [1337, 6], [1381, 6], [1436, 6], [1441, 6], [1482, 10], [1500, 6], [1613, 6], [1817, 6], [1819, 6], [1869, 6], [1881, 6], [1889, 10], [1909, 6], [1911, 6], [1920, 6], [1949, 6], [1957, 10], [2039, 6], [2039, 10], [2059, 6], [2060, 6], [2217, 6], [2220, 10], [2227, 6], [2283, 6], [2296, 6], [2349, 6], [2350, 6], [2351, 6], [2362, 6], [2363, 6], [2365, 6], [2368, 6], [2371, 6], [2

109

In [0]:
for indeces in unclean:
  print(unnumFeatures92[indeces[0],:])

[7 1978 50 5 0 3 1 2 12.2 7.79999999999999 'N' 13]
[9 1945 300 4 0 4 'A' 1 19.5 4.9 1 26]
[7 1951 30 1 13 4 'A' 1 25.9 5.29999999999999 2 12]
[7 1952 10 2 33 4 'A' 1 27.7 6.7 6 19]
[7 1980 150 4 0 4 'A' 1 25.3 7.29999999999999 6 11]
[7 1984 200 5 20 4 'A' 1 22.3 7.5 3 7]
[7 1985 100 5 20 4 'A' 1 22.3 7.29999999999999 3 7]
[7 1978 200 6 15 4 'A' 1 26.8 8.09999999999999 3 14]
[7 1988 60 6 0 4 'A' 1 42.7 5.5 2 4]
[7 1979 300 6 0 4 'A' 1 20.4 7.29999999999999 3 12]
[7 1983 800 5 10 4 'A' 1 16.8 7.29999999999999 3 8]
[7 1976 200 3 0 4 'A' 1 26.5 5.59999999999999 6 15]
[7 1986 200 5 5 4 'A' 1 22.3 6.7 3 5]
[7 1976 100 5 0 4 'A' 1 35.4 8.09999999999999 6 15]
[7 1981 130 5 20 4 'A' 1 35.1 7.29999999999999 3 10]
[7 1989 50 6 0 4 'A' 1 37.2 6.7 2 2]
[7 1982 400 5 20 4 'A' 1 16.5 8.09999999999999 6 9]
[7 1978 300 6 0 4 'A' 1 18.6 7.5 3 13]
[7 1981 700 5 5 4 'A' 1 27.4 7.29999999999999 3 10]
[7 1979 200 6 0 4 'A' 1 30.8 7.59999999999999 2 13]
[7 1984 500 5 40 4 'A' 1 68.3 7.5 3 8]
[7 1982 300 5 0 

In [0]:
print(len(unclean))

109


In [0]:
uncleanRows=[]
for i in range(len(unclean)):
  uncleanRows.append(unclean[i][0])
print(len(uncleanRows))
print(uncleanRows)

109
[29, 48, 148, 191, 201, 442, 448, 453, 469, 477, 478, 481, 483, 488, 491, 492, 514, 518, 542, 544, 545, 546, 615, 617, 618, 661, 763, 807, 808, 810, 811, 814, 815, 818, 819, 820, 975, 979, 1016, 1018, 1060, 1063, 1079, 1107, 1112, 1235, 1237, 1241, 1242, 1247, 1249, 1250, 1263, 1267, 1268, 1272, 1283, 1285, 1304, 1337, 1381, 1436, 1441, 1482, 1500, 1613, 1817, 1819, 1869, 1881, 1889, 1909, 1911, 1920, 1949, 1957, 2039, 2039, 2059, 2060, 2217, 2220, 2227, 2283, 2296, 2349, 2350, 2351, 2362, 2363, 2365, 2368, 2371, 2385, 2413, 2544, 2555, 2707, 2714, 2723, 2724, 2760, 2761, 2772, 2842, 2843, 2845, 2850, 2874]


In [0]:
cleanFeatures92 = np.delete(unnumFeatures92, uncleanRows, axis= 0)
print(np.shape(cleanFeatures92))

(2767, 12)


In [0]:
for i in range(len(cleanFeatures92)):
  print((cleanFeatures92[i,:]))

[9 1960 1920 2 10 1 2 3 34.1 12.1999999999999 1 31]
[9 1951 150 4 0 2 1 1 12.8 6.7 2 40]
[3 1954 1354 0 0 1 2 3 30.2 13.6 1 37]
[4 1940 10 0 0 2 1 1 14.3 9.0 1 51]
[4 1940 10 0 0 2 1 1 12.8 9.0 1 51]
[4 1946 850 0 0 2 1 1 16.5 7.59999999999999 1 45]
[4 1900 500 5 39 3 1 1 10.1 7.29999999999999 1 7]
[4 1900 400 5 0 3 1 1 7.3 7.29999999999999 1 7]
[4 1900 100 0 0 3 1 2 15.2 6.09999999999999 1 6]
[4 1950 100 0 0 2 1 1 8.2 6.09999999999999 2 4]
[4 1868 100 0 0 4 4 1 43.6 5.59999999999999 2 7]
[4 1973 100 0 0 2 1 1 8.5 7.59999999999999 3 18]
[4 1976 100 0 0 3 1 1 12.2 8.8 1 15]
[4 1900 200 5 0 1 1 1 8.5 6.09999999999999 2 1]
[4 1960 200 0 0 3 1 1 15.5 6.09999999999999 2 31]
[4 1900 200 5 0 3 1 1 14.9 6.09999999999999 9 10]
[4 1900 200 0 10 4 4 1 35.1 4.0 2 91]
[4 1974 100 5 0 3 1 1 11.0 7.9 1 17]
[4 1981 200 5 0 3 1 1 15.8 6.09999999999999 1 10]
[4 1990 100 6 30 3 1 1 8.5 7.29999999999999 1 1]
[4 1900 400 5 0 2 1 1 7.0 8.5 2 91]
[10 1929 4900 6 31 2 2 2 34.1 11.0 1 6]
[10 1957 460 1 0 1 2 3

In [0]:
unclean_labels = unnumData92[:,10]
print(len(unclean_labels))
cleanLabels92 = np.delete(unclean_labels, uncleanRows, axis=0)
print(len(cleanLabels92))

2875
2767


In [0]:
cleanData = np.array(list(zip(cleanFeatures92,cleanLabels92)))

In [0]:
np.shape(cleanData)

(2767, 2)

In [0]:
cleanData

array([[array([9, 1960, 1920, 2, 10, 1, 2, 3, 34.1, 12.1999999999999, 1, 31],
      dtype=object),
        6],
       [array([9, 1951, 150, 4, 0, 2, 1, 1, 12.8, 6.7, 2, 40], dtype=object),
        5],
       [array([3, 1954, 1354, 0, 0, 1, 2, 3, 30.2, 13.6, 1, 37], dtype=object),
        6],
       ...,
       [array([1, 1984, 1430, 6, 0, 2, 1, 1, 15.2, 9.8, 1, 7], dtype=object),
        8],
       [array([1, 1990, 50, 5, 0, 2, 1, 1, 15.2, 8.5, 2, 0], dtype=object),
        9],
       [array([1, 1977, 50, 5, 0, 3, 1, 1, 8.2, 6.59999999999999, 1, 13],
      dtype=object),
        7]], dtype=object)

In [0]:
cleanData[0][1]


6

In [0]:
cleanData[0][0]


array([9, 1960, 1920, 2, 10, 1, 2, 3, 34.1, 12.1999999999999, 1, 31],
      dtype=object)

In [0]:
import keras
categorical_labels=keras.utils.to_categorical(cleanLabels92)


In [0]:
training_data = np.array(list(zip(cleanFeatures92,categorical_labels)))
print(np.shape(training_data))

(2767, 2)


In [0]:
np.shape(training_data)

(2767, 2)

In [0]:
from keras.models import Sequential
from keras.layers import Dense
from keras.optimizers import Adam
from keras import metrics

In [0]:
#simple keras model
t_model = Sequential()
t_model.add(Dense(100, activation="relu"))
t_model.add(Dense(50, activation="relu"))
t_model.add(Dense(10))
t_model.compile(
    loss="mean_squared_error",
    optimizer=Adam(lr=0.001),
    metrics=[metrics.mae])

In [0]:
epochs = 500
batch = 128

In [0]:
training_data

array([[array([9, 1960, 1920, 2, 10, 1, 2, 3, 34.1, 12.1999999999999, 1, 31],
      dtype=object),
        array([0., 0., 0., 0., 0., 0., 1., 0., 0., 0.], dtype=float32)],
       [array([9, 1951, 150, 4, 0, 2, 1, 1, 12.8, 6.7, 2, 40], dtype=object),
        array([0., 0., 0., 0., 0., 1., 0., 0., 0., 0.], dtype=float32)],
       [array([3, 1954, 1354, 0, 0, 1, 2, 3, 30.2, 13.6, 1, 37], dtype=object),
        array([0., 0., 0., 0., 0., 0., 1., 0., 0., 0.], dtype=float32)],
       ...,
       [array([1, 1984, 1430, 6, 0, 2, 1, 1, 15.2, 9.8, 1, 7], dtype=object),
        array([0., 0., 0., 0., 0., 0., 0., 0., 1., 0.], dtype=float32)],
       [array([1, 1990, 50, 5, 0, 2, 1, 1, 15.2, 8.5, 2, 0], dtype=object),
        array([0., 0., 0., 0., 0., 0., 0., 0., 0., 1.], dtype=float32)],
       [array([1, 1977, 50, 5, 0, 3, 1, 1, 8.2, 6.59999999999999, 1, 13],
      dtype=object),
        array([0., 0., 0., 0., 0., 0., 0., 1., 0., 0.], dtype=float32)]],
      dtype=object)

In [0]:
history = t_model.fit(
    x = cleanFeatures92,
    y = categorical_labels,
    batch_size=batch,
    epochs=epochs,
    shuffle=True,
    verbose=1,
    callbacks=[]
)






Epoch 1/500





2767/2767 [==============================] - 9s 3ms/step - loss: 111585.2783 - mean_absolute_error: 110.4001
Epoch 2/500
2767/2767 [==============================] - 0s 25us/step - loss: 9827.2295 - mean_absolute_error: 48.2633
Epoch 3/500
2767/2767 [==============================] - 0s 23us/step - loss: 2473.0336 - mean_absolute_error: 25.2071
Epoch 4/500
2767/2767 [==============================] - 0s 32us/step - loss: 702.7297 - mean_absolute_error: 15.7948
Epoch 5/500
2767/2767 [==============================] - 0s 23us/step - loss: 510.6882 - mean_absolute_error: 12.4468
Epoch 6/500
2767/2767 [==============================] - 0s 23us/step - loss: 339.5987 - mean_absolute_error: 10.8605
Epoch 7/500
2767/2767 [==============================] - 0s 24us/step - loss: 250.2128 - mean_absolute_error: 8.9215
Epoch 8/500
2767/2767 [==============================] - 0s 25us/step - loss: 174.3955 - mean_absolute_error: 8.0213
Epoch 9/500
2767/2767 [=====================

NameError: ignored